"use client";
import { useActionState, useState } from "react";
import { checkoutAction } from "@/app/actions/checkout";
import type { AuthUser } from "@/lib/auth/types";
import type { Cart } from "@/lib/cart/types";

const field = "mt-2 h-12 w-full rounded-xl border border-slate-200 px-4 outline-none focus:border-emerald-600";
export function CheckoutForm({ user, cart, idempotencyKey }: { user: AuthUser; cart: Cart; idempotencyKey: string }) {
  const [state, action, pending] = useActionState(checkoutAction, {}); const [mode, setMode] = useState("HOME_DELIVERY");
  const fee = mode === "HOME_DELIVERY" ? 20000 : 0;
  return <form action={action} className="grid gap-8 lg:grid-cols-[1fr_360px]"><input type="hidden" name="idempotencyKey" value={idempotencyKey} /><section className="rounded-3xl bg-white p-6 shadow-sm sm:p-8"><h1 className="text-2xl font-bold text-emerald-950">Livraison</h1><div className="mt-6 grid gap-5 sm:grid-cols-2"><Label title="Nom du destinataire"><input required name="recipientName" defaultValue={`${user.firstName} ${user.lastName}`} className={field} /></Label><Label title="Téléphone"><input required name="recipientPhone" defaultValue={user.phone} className={field} /></Label></div><fieldset className="mt-6"><legend className="font-semibold">Mode de réception</legend><div className="mt-3 grid gap-3 sm:grid-cols-2"><Choice value="HOME_DELIVERY" checked={mode === "HOME_DELIVERY"} onChange={setMode} title="Livraison à domicile" detail="20 000 GNF · Conakry" /><Choice value="PICKUP" checked={mode === "PICKUP"} onChange={setMode} title="Retrait" detail="Gratuit" /></div></fieldset>{mode === "HOME_DELIVERY" && <div className="mt-6 grid gap-5 sm:grid-cols-2"><Label title="Ville"><input required name="city" defaultValue="Conakry" className={field} /></Label><Label title="Quartier"><input required name="district" className={field} /></Label><div className="sm:col-span-2"><Label title="Adresse précise"><input required name="addressLine" className={field} placeholder="Rue, repère, bâtiment…" /></Label></div></div>}<Label title="Instructions (facultatif)"><textarea name="deliveryNotes" rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-4" /></Label>{state.message && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{state.message}</p>}</section><aside className="h-fit rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-emerald-950">Votre commande</h2><div className="mt-5 space-y-3">{cart.items.map(item => <div key={item.productSlug} className="flex justify-between gap-4 text-sm"><span>{item.quantity} × {item.name}</span><strong>{item.lineTotalGnf.toLocaleString("fr-FR")} GNF</strong></div>)}</div><div className="mt-5 space-y-3 border-t pt-5 text-sm"><p className="flex justify-between"><span>Sous-total</span><span>{cart.subtotalGnf.toLocaleString("fr-FR")} GNF</span></p><p className="flex justify-between"><span>Livraison</span><span>{fee.toLocaleString("fr-FR")} GNF</span></p><p className="flex justify-between text-lg font-bold"><span>Total</span><span>{(cart.subtotalGnf + fee).toLocaleString("fr-FR")} GNF</span></p></div><button disabled={pending} className="mt-6 h-12 w-full rounded-xl bg-emerald-700 font-semibold text-white disabled:opacity-60">{pending ? "Création…" : "Confirmer la commande"}</button><p className="mt-3 text-xs text-slate-500">Vous choisirez le paiement à l’étape suivante.</p></aside></form>;
}
function Label({ title, children }: { title: string; children: React.ReactNode }) { return <label className="mt-5 block text-sm font-medium text-slate-700">{title}{children}</label>; }
function Choice({ value, checked, onChange, title, detail }: { value: string; checked: boolean; onChange: (value: string) => void; title: string; detail: string }) { return <label className={`cursor-pointer rounded-xl border p-4 ${checked ? "border-emerald-600 bg-emerald-50" : "border-slate-200"}`}><input type="radio" name="deliveryMode" value={value} checked={checked} onChange={() => onChange(value)} className="mr-2" /><strong>{title}</strong><span className="mt-1 block pl-6 text-xs text-slate-500">{detail}</span></label>; }
